version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sass
  - dependency-name: sass-loader
    versions:
    - "> 11.0.0, < 12"
  - dependency-name: sass-loader
    versions:
    - ">= 11.a, < 12"
  - dependency-name: eslint
    versions:
    - 7.24.0
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.2.1
